# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SDC_GUI_1.ui'
#
# Created: Wed Apr 20 00:19:45 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1515, 942)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 661))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.group_setup_sources = QtGui.QGroupBox(self.groupBox)
        self.group_setup_sources.setGeometry(QtCore.QRect(10, 20, 331, 521))
        self.group_setup_sources.setObjectName(_fromUtf8("group_setup_sources"))
        self.label = QtGui.QLabel(self.group_setup_sources)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.cmb_camera_source = QtGui.QComboBox(self.group_setup_sources)
        self.cmb_camera_source.setGeometry(QtCore.QRect(150, 30, 141, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.cmb_camera_source.setFont(font)
        self.cmb_camera_source.setObjectName(_fromUtf8("cmb_camera_source"))
        self.cmb_camera_source.addItem(_fromUtf8(""))
        self.cmb_camera_source.addItem(_fromUtf8(""))
        self.cmb_camera_source.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.group_setup_sources)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txte_camera_host = QtGui.QLineEdit(self.group_setup_sources)
        self.txte_camera_host.setGeometry(QtCore.QRect(150, 70, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(6)
        self.txte_camera_host.setFont(font)
        self.txte_camera_host.setObjectName(_fromUtf8("txte_camera_host"))
        self.label_3 = QtGui.QLabel(self.group_setup_sources)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.txt_neuron_path = QtGui.QLabel(self.group_setup_sources)
        self.txt_neuron_path.setGeometry(QtCore.QRect(150, 240, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_neuron_path.setFont(font)
        self.txt_neuron_path.setObjectName(_fromUtf8("txt_neuron_path"))
        self.btn_browse_training_folder = QtGui.QPushButton(self.group_setup_sources)
        self.btn_browse_training_folder.setGeometry(QtCore.QRect(150, 210, 75, 23))
        self.btn_browse_training_folder.setObjectName(_fromUtf8("btn_browse_training_folder"))
        self.label_5 = QtGui.QLabel(self.group_setup_sources)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txt_training_folder_path = QtGui.QLabel(self.group_setup_sources)
        self.txt_training_folder_path.setGeometry(QtCore.QRect(150, 190, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_training_folder_path.setFont(font)
        self.txt_training_folder_path.setObjectName(_fromUtf8("txt_training_folder_path"))
        self.btn_browse_neuron = QtGui.QPushButton(self.group_setup_sources)
        self.btn_browse_neuron.setGeometry(QtCore.QRect(150, 260, 75, 23))
        self.btn_browse_neuron.setObjectName(_fromUtf8("btn_browse_neuron"))
        self.btn_create_neurone = QtGui.QPushButton(self.group_setup_sources)
        self.btn_create_neurone.setGeometry(QtCore.QRect(230, 260, 75, 23))
        self.btn_create_neurone.setObjectName(_fromUtf8("btn_create_neurone"))
        self.cmb_serial_port = QtGui.QComboBox(self.group_setup_sources)
        self.cmb_serial_port.setGeometry(QtCore.QRect(150, 110, 141, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.cmb_serial_port.setFont(font)
        self.cmb_serial_port.setObjectName(_fromUtf8("cmb_serial_port"))
        self.cmb_serial_port.addItem(_fromUtf8(""))
        self.cmb_serial_port.addItem(_fromUtf8(""))
        self.cmb_serial_port.addItem(_fromUtf8(""))
        self.cmb_serial_port.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.group_setup_sources)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cmb_camera_size = QtGui.QComboBox(self.group_setup_sources)
        self.cmb_camera_size.setGeometry(QtCore.QRect(150, 150, 141, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.cmb_camera_size.setFont(font)
        self.cmb_camera_size.setObjectName(_fromUtf8("cmb_camera_size"))
        self.cmb_camera_size.addItem(_fromUtf8(""))
        self.cmb_camera_size.addItem(_fromUtf8(""))
        self.cmb_camera_size.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.group_setup_sources)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.group_setup_sources)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.txt_haar_path = QtGui.QLabel(self.group_setup_sources)
        self.txt_haar_path.setGeometry(QtCore.QRect(150, 290, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_haar_path.setFont(font)
        self.txt_haar_path.setObjectName(_fromUtf8("txt_haar_path"))
        self.btn_browse_haar = QtGui.QPushButton(self.group_setup_sources)
        self.btn_browse_haar.setGeometry(QtCore.QRect(150, 310, 75, 23))
        self.btn_browse_haar.setObjectName(_fromUtf8("btn_browse_haar"))
        self.btn_create_haar = QtGui.QPushButton(self.group_setup_sources)
        self.btn_create_haar.setGeometry(QtCore.QRect(230, 310, 75, 23))
        self.btn_create_haar.setObjectName(_fromUtf8("btn_create_haar"))
        self.label_11 = QtGui.QLabel(self.group_setup_sources)
        self.label_11.setGeometry(QtCore.QRect(20, 340, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lst_mlp_layers = QtGui.QListWidget(self.group_setup_sources)
        self.lst_mlp_layers.setGeometry(QtCore.QRect(150, 350, 71, 111))
        self.lst_mlp_layers.setObjectName(_fromUtf8("lst_mlp_layers"))
        self.btn_add_layer = QtGui.QPushButton(self.group_setup_sources)
        self.btn_add_layer.setGeometry(QtCore.QRect(230, 350, 75, 23))
        self.btn_add_layer.setObjectName(_fromUtf8("btn_add_layer"))
        self.btn_remove_layer = QtGui.QPushButton(self.group_setup_sources)
        self.btn_remove_layer.setGeometry(QtCore.QRect(230, 380, 75, 23))
        self.btn_remove_layer.setObjectName(_fromUtf8("btn_remove_layer"))
        self.btn_init_sdc = QtGui.QCommandLinkButton(self.group_setup_sources)
        self.btn_init_sdc.setGeometry(QtCore.QRect(70, 470, 185, 41))
        self.btn_init_sdc.setObjectName(_fromUtf8("btn_init_sdc"))
        self.group_workarea = QtGui.QGroupBox(self.centralwidget)
        self.group_workarea.setGeometry(QtCore.QRect(400, 10, 1011, 841))
        self.group_workarea.setObjectName(_fromUtf8("group_workarea"))
        self.label_36 = QtGui.QLabel(self.group_workarea)
        self.label_36.setGeometry(QtCore.QRect(210, 30, 681, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(93, 93, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 93, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_36.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.btn_stop_sdc_system = QtGui.QCommandLinkButton(self.group_workarea)
        self.btn_stop_sdc_system.setGeometry(QtCore.QRect(10, 30, 185, 41))
        self.btn_stop_sdc_system.setObjectName(_fromUtf8("btn_stop_sdc_system"))
        self.groupBox_4 = QtGui.QGroupBox(self.group_workarea)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 80, 971, 741))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 9, 931, 151))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.txt_camera_source = QtGui.QLabel(self.groupBox_6)
        self.txt_camera_source.setGeometry(QtCore.QRect(150, 20, 401, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_camera_source.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_camera_source.setFont(font)
        self.txt_camera_source.setObjectName(_fromUtf8("txt_camera_source"))
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(20, 50, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.txt_input_neuron = QtGui.QLabel(self.groupBox_6)
        self.txt_input_neuron.setGeometry(QtCore.QRect(150, 50, 161, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_input_neuron.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_input_neuron.setFont(font)
        self.txt_input_neuron.setObjectName(_fromUtf8("txt_input_neuron"))
        self.txt_hidden_neuron = QtGui.QLabel(self.groupBox_6)
        self.txt_hidden_neuron.setGeometry(QtCore.QRect(150, 80, 171, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_hidden_neuron.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_hidden_neuron.setFont(font)
        self.txt_hidden_neuron.setObjectName(_fromUtf8("txt_hidden_neuron"))
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(20, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.txt_total_synapsis = QtGui.QLabel(self.groupBox_6)
        self.txt_total_synapsis.setGeometry(QtCore.QRect(150, 110, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_total_synapsis.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_total_synapsis.setFont(font)
        self.txt_total_synapsis.setObjectName(_fromUtf8("txt_total_synapsis"))
        self.mlp_status_box = QtGui.QGroupBox(self.groupBox_4)
        self.mlp_status_box.setGeometry(QtCore.QRect(20, 170, 271, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.mlp_status_box.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mlp_status_box.setFont(font)
        self.mlp_status_box.setTitle(_fromUtf8(""))
        self.mlp_status_box.setObjectName(_fromUtf8("mlp_status_box"))
        self.cmb_camera_mode = QtGui.QComboBox(self.mlp_status_box)
        self.cmb_camera_mode.setGeometry(QtCore.QRect(140, 30, 111, 22))
        self.cmb_camera_mode.setObjectName(_fromUtf8("cmb_camera_mode"))
        self.cmb_camera_mode.addItem(_fromUtf8(""))
        self.cmb_camera_mode.addItem(_fromUtf8(""))
        self.cmb_camera_mode.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.mlp_status_box)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cbx_visualize_camera = QtGui.QCheckBox(self.mlp_status_box)
        self.cbx_visualize_camera.setGeometry(QtCore.QRect(30, 70, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.cbx_visualize_camera.setFont(font)
        self.cbx_visualize_camera.setObjectName(_fromUtf8("cbx_visualize_camera"))
        self.cbx_visualize_sensor = QtGui.QCheckBox(self.mlp_status_box)
        self.cbx_visualize_sensor.setGeometry(QtCore.QRect(30, 100, 171, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.cbx_visualize_sensor.setFont(font)
        self.cbx_visualize_sensor.setObjectName(_fromUtf8("cbx_visualize_sensor"))
        self.label_48 = QtGui.QLabel(self.mlp_status_box)
        self.label_48.setGeometry(QtCore.QRect(20, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.txt_wheel_state = QtGui.QLabel(self.mlp_status_box)
        self.txt_wheel_state.setGeometry(QtCore.QRect(140, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_wheel_state.setFont(font)
        self.txt_wheel_state.setObjectName(_fromUtf8("txt_wheel_state"))
        self.label_49 = QtGui.QLabel(self.mlp_status_box)
        self.label_49.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.txt_traffic_sign = QtGui.QLabel(self.mlp_status_box)
        self.txt_traffic_sign.setGeometry(QtCore.QRect(160, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_traffic_sign.setFont(font)
        self.txt_traffic_sign.setObjectName(_fromUtf8("txt_traffic_sign"))
        self.label_54 = QtGui.QLabel(self.mlp_status_box)
        self.label_54.setGeometry(QtCore.QRect(20, 190, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.txt_object_distance = QtGui.QLabel(self.mlp_status_box)
        self.txt_object_distance.setGeometry(QtCore.QRect(160, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_object_distance.setFont(font)
        self.txt_object_distance.setObjectName(_fromUtf8("txt_object_distance"))
        self.mlp_status_box_2 = QtGui.QGroupBox(self.groupBox_4)
        self.mlp_status_box_2.setGeometry(QtCore.QRect(350, 170, 271, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.mlp_status_box_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mlp_status_box_2.setFont(font)
        self.mlp_status_box_2.setObjectName(_fromUtf8("mlp_status_box_2"))
        self.txt_mlp1_training_images = QtGui.QLabel(self.mlp_status_box_2)
        self.txt_mlp1_training_images.setGeometry(QtCore.QRect(20, 20, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.txt_mlp1_training_images.setFont(font)
        self.txt_mlp1_training_images.setObjectName(_fromUtf8("txt_mlp1_training_images"))
        self.txt_mlp1_batch_number = QtGui.QLabel(self.mlp_status_box_2)
        self.txt_mlp1_batch_number.setGeometry(QtCore.QRect(20, 40, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.txt_mlp1_batch_number.setFont(font)
        self.txt_mlp1_batch_number.setObjectName(_fromUtf8("txt_mlp1_batch_number"))
        self.txt_mlp1_loop_number = QtGui.QLabel(self.mlp_status_box_2)
        self.txt_mlp1_loop_number.setGeometry(QtCore.QRect(20, 70, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.txt_mlp1_loop_number.setFont(font)
        self.txt_mlp1_loop_number.setObjectName(_fromUtf8("txt_mlp1_loop_number"))
        self.label_27 = QtGui.QLabel(self.mlp_status_box_2)
        self.label_27.setGeometry(QtCore.QRect(20, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.prg_mlp1_percent = QtGui.QProgressBar(self.mlp_status_box_2)
        self.prg_mlp1_percent.setGeometry(QtCore.QRect(20, 170, 231, 23))
        self.prg_mlp1_percent.setProperty("value", 24)
        self.prg_mlp1_percent.setObjectName(_fromUtf8("prg_mlp1_percent"))
        self.btn_mlp1_start = QtGui.QPushButton(self.mlp_status_box_2)
        self.btn_mlp1_start.setGeometry(QtCore.QRect(20, 200, 51, 23))
        self.btn_mlp1_start.setObjectName(_fromUtf8("btn_mlp1_start"))
        self.btn_mlp1_stop = QtGui.QPushButton(self.mlp_status_box_2)
        self.btn_mlp1_stop.setGeometry(QtCore.QRect(80, 200, 51, 23))
        self.btn_mlp1_stop.setObjectName(_fromUtf8("btn_mlp1_stop"))
        self.btn_mlp1_load = QtGui.QPushButton(self.mlp_status_box_2)
        self.btn_mlp1_load.setGeometry(QtCore.QRect(140, 200, 51, 23))
        self.btn_mlp1_load.setObjectName(_fromUtf8("btn_mlp1_load"))
        self.prg_mlp1_accuracy = QtGui.QProgressBar(self.mlp_status_box_2)
        self.prg_mlp1_accuracy.setGeometry(QtCore.QRect(160, 140, 91, 20))
        self.prg_mlp1_accuracy.setProperty("value", 90)
        self.prg_mlp1_accuracy.setObjectName(_fromUtf8("prg_mlp1_accuracy"))
        self.dial_mlp1_batch = QtGui.QDial(self.mlp_status_box_2)
        self.dial_mlp1_batch.setGeometry(QtCore.QRect(170, 40, 41, 41))
        self.dial_mlp1_batch.setMinimum(1)
        self.dial_mlp1_batch.setMaximum(1000)
        self.dial_mlp1_batch.setSingleStep(10)
        self.dial_mlp1_batch.setProperty("value", 30)
        self.dial_mlp1_batch.setObjectName(_fromUtf8("dial_mlp1_batch"))
        self.dial_mlp1_loop = QtGui.QDial(self.mlp_status_box_2)
        self.dial_mlp1_loop.setGeometry(QtCore.QRect(200, 70, 41, 41))
        self.dial_mlp1_loop.setMinimum(1)
        self.dial_mlp1_loop.setMaximum(10000)
        self.dial_mlp1_loop.setSingleStep(50)
        self.dial_mlp1_loop.setProperty("value", 30)
        self.dial_mlp1_loop.setObjectName(_fromUtf8("dial_mlp1_loop"))
        self.btn_mlp1_save = QtGui.QPushButton(self.mlp_status_box_2)
        self.btn_mlp1_save.setGeometry(QtCore.QRect(200, 200, 51, 23))
        self.btn_mlp1_save.setObjectName(_fromUtf8("btn_mlp1_save"))
        self.txt_mlp1_epsilon = QtGui.QLabel(self.mlp_status_box_2)
        self.txt_mlp1_epsilon.setGeometry(QtCore.QRect(20, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.txt_mlp1_epsilon.setFont(font)
        self.txt_mlp1_epsilon.setObjectName(_fromUtf8("txt_mlp1_epsilon"))
        self.dial_mlp1_epsilon = QtGui.QDial(self.mlp_status_box_2)
        self.dial_mlp1_epsilon.setGeometry(QtCore.QRect(120, 100, 41, 41))
        self.dial_mlp1_epsilon.setMinimum(1)
        self.dial_mlp1_epsilon.setMaximum(100)
        self.dial_mlp1_epsilon.setSingleStep(1)
        self.dial_mlp1_epsilon.setProperty("value", 2)
        self.dial_mlp1_epsilon.setObjectName(_fromUtf8("dial_mlp1_epsilon"))
        self.mlp_status_box_3 = QtGui.QGroupBox(self.groupBox_4)
        self.mlp_status_box_3.setGeometry(QtCore.QRect(680, 170, 271, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.mlp_status_box_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mlp_status_box_3.setFont(font)
        self.mlp_status_box_3.setObjectName(_fromUtf8("mlp_status_box_3"))
        self.label_29 = QtGui.QLabel(self.mlp_status_box_3)
        self.label_29.setGeometry(QtCore.QRect(20, 20, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.mlp_status_box_3)
        self.label_30.setGeometry(QtCore.QRect(20, 40, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.mlp_status_box_3)
        self.label_31.setGeometry(QtCore.QRect(20, 70, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.mlp_status_box_3)
        self.label_32.setGeometry(QtCore.QRect(20, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.progressBar_5 = QtGui.QProgressBar(self.mlp_status_box_3)
        self.progressBar_5.setGeometry(QtCore.QRect(20, 170, 231, 23))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.pushButton_17 = QtGui.QPushButton(self.mlp_status_box_3)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 200, 51, 23))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.mlp_status_box_3)
        self.pushButton_18.setGeometry(QtCore.QRect(80, 200, 51, 23))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.mlp_status_box_3)
        self.pushButton_19.setGeometry(QtCore.QRect(140, 200, 51, 23))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.progressBar_6 = QtGui.QProgressBar(self.mlp_status_box_3)
        self.progressBar_6.setGeometry(QtCore.QRect(160, 140, 91, 20))
        self.progressBar_6.setProperty("value", 90)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.dial_6 = QtGui.QDial(self.mlp_status_box_3)
        self.dial_6.setGeometry(QtCore.QRect(170, 40, 41, 41))
        self.dial_6.setMinimum(1)
        self.dial_6.setMaximum(1000)
        self.dial_6.setSingleStep(10)
        self.dial_6.setProperty("value", 30)
        self.dial_6.setObjectName(_fromUtf8("dial_6"))
        self.dial_7 = QtGui.QDial(self.mlp_status_box_3)
        self.dial_7.setGeometry(QtCore.QRect(200, 70, 41, 41))
        self.dial_7.setMinimum(1)
        self.dial_7.setMaximum(10000)
        self.dial_7.setSingleStep(50)
        self.dial_7.setProperty("value", 30)
        self.dial_7.setObjectName(_fromUtf8("dial_7"))
        self.pushButton_20 = QtGui.QPushButton(self.mlp_status_box_3)
        self.pushButton_20.setGeometry(QtCore.QRect(200, 200, 51, 23))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.label_33 = QtGui.QLabel(self.mlp_status_box_3)
        self.label_33.setGeometry(QtCore.QRect(20, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.dial_8 = QtGui.QDial(self.mlp_status_box_3)
        self.dial_8.setGeometry(QtCore.QRect(120, 100, 41, 41))
        self.dial_8.setMinimum(1)
        self.dial_8.setMaximum(100)
        self.dial_8.setSingleStep(1)
        self.dial_8.setProperty("value", 2)
        self.dial_8.setObjectName(_fromUtf8("dial_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 420, 931, 301))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.grp_free_mode = QtGui.QGroupBox(self.groupBox_5)
        self.grp_free_mode.setGeometry(QtCore.QRect(20, 30, 251, 251))
        self.grp_free_mode.setCheckable(True)
        self.grp_free_mode.setChecked(True)
        self.grp_free_mode.setObjectName(_fromUtf8("grp_free_mode"))
        self.label_34 = QtGui.QLabel(self.grp_free_mode)
        self.label_34.setGeometry(QtCore.QRect(20, 170, 61, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.bar_free_mode_speed = QtGui.QSlider(self.grp_free_mode)
        self.bar_free_mode_speed.setGeometry(QtCore.QRect(90, 170, 131, 22))
        self.bar_free_mode_speed.setMinimum(1)
        self.bar_free_mode_speed.setMaximum(6)
        self.bar_free_mode_speed.setSingleStep(1)
        self.bar_free_mode_speed.setProperty("value", 2)
        self.bar_free_mode_speed.setOrientation(QtCore.Qt.Horizontal)
        self.bar_free_mode_speed.setObjectName(_fromUtf8("bar_free_mode_speed"))
        self.btn_free_mode_start = QtGui.QCommandLinkButton(self.grp_free_mode)
        self.btn_free_mode_start.setGeometry(QtCore.QRect(50, 200, 151, 41))
        self.btn_free_mode_start.setObjectName(_fromUtf8("btn_free_mode_start"))
        self.groupBox_13 = QtGui.QGroupBox(self.grp_free_mode)
        self.groupBox_13.setGeometry(QtCore.QRect(140, 60, 31, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_13.setPalette(palette)
        self.groupBox_13.setAutoFillBackground(True)
        self.groupBox_13.setTitle(_fromUtf8(""))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.groupBox_14 = QtGui.QGroupBox(self.grp_free_mode)
        self.groupBox_14.setGeometry(QtCore.QRect(50, 40, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_14.setPalette(palette)
        self.groupBox_14.setAutoFillBackground(True)
        self.groupBox_14.setTitle(_fromUtf8(""))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.groupBox_15 = QtGui.QGroupBox(self.grp_free_mode)
        self.groupBox_15.setGeometry(QtCore.QRect(50, 80, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_15.setPalette(palette)
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setTitle(_fromUtf8(""))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.groupBox_16 = QtGui.QGroupBox(self.grp_free_mode)
        self.groupBox_16.setGeometry(QtCore.QRect(200, 60, 31, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_16.setPalette(palette)
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_16.setTitle(_fromUtf8(""))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.grp_self_driving = QtGui.QGroupBox(self.groupBox_5)
        self.grp_self_driving.setGeometry(QtCore.QRect(290, 30, 301, 251))
        self.grp_self_driving.setCheckable(True)
        self.grp_self_driving.setChecked(True)
        self.grp_self_driving.setObjectName(_fromUtf8("grp_self_driving"))
        self.grp_selfdriving = QtGui.QGroupBox(self.grp_self_driving)
        self.grp_selfdriving.setGeometry(QtCore.QRect(20, 50, 261, 191))
        self.grp_selfdriving.setTitle(_fromUtf8(""))
        self.grp_selfdriving.setObjectName(_fromUtf8("grp_selfdriving"))
        self.bar_self_driving_speed = QtGui.QSlider(self.grp_selfdriving)
        self.bar_self_driving_speed.setGeometry(QtCore.QRect(90, 20, 151, 22))
        self.bar_self_driving_speed.setMinimum(1)
        self.bar_self_driving_speed.setMaximum(6)
        self.bar_self_driving_speed.setSingleStep(1)
        self.bar_self_driving_speed.setProperty("value", 2)
        self.bar_self_driving_speed.setOrientation(QtCore.Qt.Horizontal)
        self.bar_self_driving_speed.setObjectName(_fromUtf8("bar_self_driving_speed"))
        self.label_35 = QtGui.QLabel(self.grp_selfdriving)
        self.label_35.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.cbx_detect_sign = QtGui.QCheckBox(self.grp_selfdriving)
        self.cbx_detect_sign.setGeometry(QtCore.QRect(20, 110, 141, 17))
        self.cbx_detect_sign.setObjectName(_fromUtf8("cbx_detect_sign"))
        self.bar_self_driving_frame = QtGui.QSlider(self.grp_selfdriving)
        self.bar_self_driving_frame.setGeometry(QtCore.QRect(90, 50, 151, 22))
        self.bar_self_driving_frame.setMinimum(1)
        self.bar_self_driving_frame.setMaximum(100)
        self.bar_self_driving_frame.setProperty("value", 78)
        self.bar_self_driving_frame.setOrientation(QtCore.Qt.Horizontal)
        self.bar_self_driving_frame.setObjectName(_fromUtf8("bar_self_driving_frame"))
        self.label_37 = QtGui.QLabel(self.grp_selfdriving)
        self.label_37.setGeometry(QtCore.QRect(20, 50, 61, 21))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.bar_self_driving_near_object = QtGui.QSlider(self.grp_selfdriving)
        self.bar_self_driving_near_object.setGeometry(QtCore.QRect(90, 80, 151, 22))
        self.bar_self_driving_near_object.setMinimum(1)
        self.bar_self_driving_near_object.setMaximum(100)
        self.bar_self_driving_near_object.setProperty("value", 78)
        self.bar_self_driving_near_object.setOrientation(QtCore.Qt.Horizontal)
        self.bar_self_driving_near_object.setObjectName(_fromUtf8("bar_self_driving_near_object"))
        self.label_38 = QtGui.QLabel(self.grp_selfdriving)
        self.label_38.setGeometry(QtCore.QRect(20, 80, 61, 21))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.cbx_detect_object = QtGui.QCheckBox(self.grp_selfdriving)
        self.cbx_detect_object.setGeometry(QtCore.QRect(20, 140, 141, 17))
        self.cbx_detect_object.setObjectName(_fromUtf8("cbx_detect_object"))
        self.cbx_self_driving_visualize = QtGui.QCheckBox(self.grp_selfdriving)
        self.cbx_self_driving_visualize.setGeometry(QtCore.QRect(20, 170, 70, 17))
        self.cbx_self_driving_visualize.setObjectName(_fromUtf8("cbx_self_driving_visualize"))
        self.btn_self_driving_stop = QtGui.QPushButton(self.grp_selfdriving)
        self.btn_self_driving_stop.setGeometry(QtCore.QRect(180, 130, 75, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btn_self_driving_stop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Georgia"))
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_self_driving_stop.setFont(font)
        self.btn_self_driving_stop.setAutoFillBackground(True)
        self.btn_self_driving_stop.setObjectName(_fromUtf8("btn_self_driving_stop"))
        self.btn_self_driving_start = QtGui.QPushButton(self.grp_self_driving)
        self.btn_self_driving_start.setGeometry(QtCore.QRect(200, 20, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_self_driving_start.setFont(font)
        self.btn_self_driving_start.setObjectName(_fromUtf8("btn_self_driving_start"))
        self.grp_training = QtGui.QGroupBox(self.groupBox_5)
        self.grp_training.setGeometry(QtCore.QRect(610, 30, 301, 251))
        self.grp_training.setCheckable(True)
        self.grp_training.setChecked(True)
        self.grp_training.setObjectName(_fromUtf8("grp_training"))
        self.groupBox_11 = QtGui.QGroupBox(self.grp_training)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 30, 271, 91))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_9.setGeometry(QtCore.QRect(150, 20, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.label_39 = QtGui.QLabel(self.groupBox_11)
        self.label_39.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.pushButton_23 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_23.setGeometry(QtCore.QRect(150, 50, 75, 23))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.label_40 = QtGui.QLabel(self.groupBox_11)
        self.label_40.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.groupBox_12 = QtGui.QGroupBox(self.grp_training)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 130, 271, 101))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalSlider_5 = QtGui.QSlider(self.groupBox_12)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(130, 20, 121, 22))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.label_41 = QtGui.QLabel(self.groupBox_12)
        self.label_41.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.commandLinkButton_4 = QtGui.QCommandLinkButton(self.groupBox_12)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(170, 50, 81, 41))
        self.commandLinkButton_4.setObjectName(_fromUtf8("commandLinkButton_4"))
        self.pushButton_24 = QtGui.QPushButton(self.groupBox_12)
        self.pushButton_24.setGeometry(QtCore.QRect(20, 60, 121, 31))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1515, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Setup SDC+DAS", None))
        self.group_setup_sources.setTitle(_translate("MainWindow", "Setup Sources", None))
        self.label.setText(_translate("MainWindow", "Camera Source", None))
        self.cmb_camera_source.setItemText(0, _translate("MainWindow", "IP Camera", None))
        self.cmb_camera_source.setItemText(1, _translate("MainWindow", "USB Camera", None))
        self.cmb_camera_source.setItemText(2, _translate("MainWindow", "WebCam", None))
        self.label_2.setText(_translate("MainWindow", "Camera Host", None))
        self.label_3.setText(_translate("MainWindow", "Serial Port", None))
        self.txt_neuron_path.setText(_translate("MainWindow", "c:/My_Neural/Network/MLP.xml", None))
        self.btn_browse_training_folder.setText(_translate("MainWindow", "Browse", None))
        self.label_5.setText(_translate("MainWindow", "Training Folder", None))
        self.txt_training_folder_path.setText(_translate("MainWindow", "c:/My_Neural/Haar/Cascade.xml", None))
        self.btn_browse_neuron.setText(_translate("MainWindow", "Browse", None))
        self.btn_create_neurone.setText(_translate("MainWindow", "Create", None))
        self.cmb_serial_port.setItemText(0, _translate("MainWindow", "COM1", None))
        self.cmb_serial_port.setItemText(1, _translate("MainWindow", "COM2", None))
        self.cmb_serial_port.setItemText(2, _translate("MainWindow", "COM3", None))
        self.cmb_serial_port.setItemText(3, _translate("MainWindow", "COM4", None))
        self.label_7.setText(_translate("MainWindow", "Camera Size", None))
        self.cmb_camera_size.setItemText(0, _translate("MainWindow", "50 x 50", None))
        self.cmb_camera_size.setItemText(1, _translate("MainWindow", "100 x 100", None))
        self.cmb_camera_size.setItemText(2, _translate("MainWindow", "1000 x 1000", None))
        self.label_8.setText(_translate("MainWindow", "Neuron File", None))
        self.label_9.setText(_translate("MainWindow", "Haar Cas. File", None))
        self.txt_haar_path.setText(_translate("MainWindow", "c:/My_Neural/Network/MLP.xml", None))
        self.btn_browse_haar.setText(_translate("MainWindow", "Browse", None))
        self.btn_create_haar.setText(_translate("MainWindow", "Create", None))
        self.label_11.setText(_translate("MainWindow", "Hidden Layers", None))
        self.btn_add_layer.setText(_translate("MainWindow", "Add", None))
        self.btn_remove_layer.setText(_translate("MainWindow", "Remove", None))
        self.btn_init_sdc.setText(_translate("MainWindow", "Initialise SDC + DAS", None))
        self.group_workarea.setTitle(_translate("MainWindow", "SDC + DAS Work Area", None))
        self.label_36.setText(_translate("MainWindow", "Self Driving Car Plus Driving Assistance System", None))
        self.btn_stop_sdc_system.setText(_translate("MainWindow", "Stop SDC + DAS", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "SDC + DAS Features", None))
        self.label_12.setText(_translate("MainWindow", "Camera Source", None))
        self.txt_camera_source.setText(_translate("MainWindow", "http://192.168.43.1:8080/video", None))
        self.label_14.setText(_translate("MainWindow", "Input Neurones", None))
        self.label_16.setText(_translate("MainWindow", "Hidden Neurones", None))
        self.txt_input_neuron.setText(_translate("MainWindow", "2500", None))
        self.txt_hidden_neuron.setText(_translate("MainWindow", "10959", None))
        self.label_22.setText(_translate("MainWindow", "Total Synapsis", None))
        self.txt_total_synapsis.setText(_translate("MainWindow", "10959", None))
        self.cmb_camera_mode.setItemText(0, _translate("MainWindow", "GRAY", None))
        self.cmb_camera_mode.setItemText(1, _translate("MainWindow", "RGB", None))
        self.cmb_camera_mode.setItemText(2, _translate("MainWindow", "Binary", None))
        self.label_15.setText(_translate("MainWindow", "Camera Mode", None))
        self.cbx_visualize_camera.setText(_translate("MainWindow", "Visualize Camera", None))
        self.cbx_visualize_sensor.setText(_translate("MainWindow", "Visualize Sensor Inputs", None))
        self.label_48.setText(_translate("MainWindow", "Car Wheel Driver", None))
        self.txt_wheel_state.setText(_translate("MainWindow", "-> Not Moving", None))
        self.label_49.setText(_translate("MainWindow", "Trafic Sign Detection", None))
        self.txt_traffic_sign.setText(_translate("MainWindow", "-> No Trafic Sign", None))
        self.label_54.setText(_translate("MainWindow", "Neer Object Distance", None))
        self.txt_object_distance.setText(_translate("MainWindow", "-> 30 cm", None))
        self.mlp_status_box_2.setTitle(_translate("MainWindow", "MLP1 Status ", None))
        self.txt_mlp1_training_images.setText(_translate("MainWindow", "Training Images: 20", None))
        self.txt_mlp1_batch_number.setText(_translate("MainWindow", "Batch Number: 10", None))
        self.txt_mlp1_loop_number.setText(_translate("MainWindow", "Repitition Number: 100", None))
        self.label_27.setText(_translate("MainWindow", "Training Accuracy:", None))
        self.btn_mlp1_start.setText(_translate("MainWindow", "Start", None))
        self.btn_mlp1_stop.setText(_translate("MainWindow", "Stop", None))
        self.btn_mlp1_load.setText(_translate("MainWindow", "Load", None))
        self.btn_mlp1_save.setText(_translate("MainWindow", "Save", None))
        self.txt_mlp1_epsilon.setText(_translate("MainWindow", "Epsilon: 0.5", None))
        self.mlp_status_box_3.setTitle(_translate("MainWindow", "MLP2 Status ", None))
        self.label_29.setText(_translate("MainWindow", "Training Images: 20", None))
        self.label_30.setText(_translate("MainWindow", "Batch Number: 10", None))
        self.label_31.setText(_translate("MainWindow", "Repitition Number: 100", None))
        self.label_32.setText(_translate("MainWindow", "Training Accuracy:", None))
        self.pushButton_17.setText(_translate("MainWindow", "Start", None))
        self.pushButton_18.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_19.setText(_translate("MainWindow", "Load", None))
        self.pushButton_20.setText(_translate("MainWindow", "Save", None))
        self.label_33.setText(_translate("MainWindow", "Epsilon: 0.5", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Toy Car Status", None))
        self.grp_free_mode.setTitle(_translate("MainWindow", "Free Mode", None))
        self.label_34.setText(_translate("MainWindow", "Car Speed", None))
        self.btn_free_mode_start.setText(_translate("MainWindow", "Ride Free Mode", None))
        self.grp_self_driving.setTitle(_translate("MainWindow", "Self Driving", None))
        self.label_35.setText(_translate("MainWindow", "Car Speed", None))
        self.cbx_detect_sign.setText(_translate("MainWindow", "Trafic Sign Detection", None))
        self.label_37.setText(_translate("MainWindow", "Frame Rate", None))
        self.label_38.setText(_translate("MainWindow", "Near Object", None))
        self.cbx_detect_object.setText(_translate("MainWindow", "Near Object Detection", None))
        self.cbx_self_driving_visualize.setText(_translate("MainWindow", "Visulize", None))
        self.btn_self_driving_stop.setText(_translate("MainWindow", "STOP", None))
        self.btn_self_driving_start.setText(_translate("MainWindow", "Start", None))
        self.grp_training.setTitle(_translate("MainWindow", "Trainning Mode", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Train Trafic Sign (TTS)", None))
        self.pushButton_9.setText(_translate("MainWindow", "Browse", None))
        self.label_39.setText(_translate("MainWindow", "Import Trafic Signs", None))
        self.pushButton_23.setText(_translate("MainWindow", "Delete All", None))
        self.label_40.setText(_translate("MainWindow", "Remove All Trafic Signs", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Train Driving on Road", None))
        self.label_41.setText(_translate("MainWindow", "Image Sampling Rate", None))
        self.commandLinkButton_4.setText(_translate("MainWindow", "Start", None))
        self.pushButton_24.setText(_translate("MainWindow", "Remove All Training", None))


class MyMainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MyMainWindow, self).__init__(parent)
        self.setupUi(self)
        # if you didn't subclass Ui_MainWindow simply do:
        # Ui_MainWindow().setupUi(self)

    def keyPressEvent(self, e):
        print e.key()

if __name__ == '__main__':
    app = QtGui.QApplication([])
    win = MyMainWindow()
    win.show()
    app.exec_()
